"""Script generated by ansys-mapdl-core version 0.58.9"""
# Created by Basil J. Paudel            5/13/2021
# This macro will export the nodal coordinates and the deformation results
# to a CSV file

# Imports
import os
from array import *

#from ansys.mapdl.core import launch_mapdl
from ansys.mapdl import reader as Reader
#from ansys.dpf.core import Model


def find_files(filename, search_path):
   result = []

# Wlaking top-down from the root
   for root, dir, files in os.walk(search_path):
      if filename in files:
         result.append(os.path.join(root, filename))
   return result
# End def

# Filter for exporting solutions
#   Need to adjust criterio accordingly
def can_reject(tStep, lastTStep):
    if(lastTStep<-1):
        lastTStep=-1
           
    if (tStep <800/5*60 or tStep > (1350/5*60+4*3600)):
        newTStep =tStep//500
        if(lastTStep==newTStep):
            return True,lastTStep
        else:
            lastTStep=newTStep
            return False,lastTStep
    elif (tStep < (1250/5*60)):
        newTStep =tStep//250
        if(lastTStep==newTStep):
            lastTStep=newTStep
            return True,lastTStep
        else:
            lastTStep=newTStep
            return False,lastTStep
    elif (tStep < (1350/5*60+1*3600)):
        newTStep =tStep//50
        if(lastTStep==newTStep):
            lastTStep=newTStep
            return True,lastTStep
        else:
            lastTStep=newTStep
            return False,lastTStep
    elif (tStep < (1350/5*60+4*3600)):
        newTStep =tStep//250
        if(lastTStep==newTStep):
            lastTStep=newTStep
            return True,lastTStep
        else:
            lastTStep=newTStep
            return False,lastTStep
    else:
        newTStep =tStep//500
        if(lastTStep==newTStep):
            lastTStep=newTStep
            return True,lastTStep
        else:
            lastTStep=newTStep
            return False,lastTStep
        
# End function definition


# Define variables and constants
workdir = 'E:\\Basil\\DefComp\\'
path = "D:\\Basil\\WorkBench_Validation\\CD1\\Validation_CD1_Mar12_files\\dp0\\SYS\\MECH\\"

# INPUT
fname = "file.rst"
fullnameInput = path+fname
# path = os.getcwd()
workdir = path
print(path)

# OUTPUT
outputFile="Result_T"
outputDir = workdir + "Results\\"
# Directly output to OneDrive
outputDir = "D:\\Basil\\OneDrive - University of Pittsburgh\\Shared\\Hao\\BinderJet Distortion Data\\SimulationTimeHistory\\"
try:
    if (os.path.exists(outputDir) == False):
        os.mkdir(outputDir)
except OSError as error:
    print('Error Creating folder')
    
# mapdl = launch_mapdl("True", loglevel="WARNING")
# Sample result file
rstfile = fullnameInput

# Create result object by loading the result file
# Working with result after simulation
result = Reader.read_binary(rstfile)  # Using Reader

# Get result using dpf
#mdl = Model(rstfile)
##rslt = mdl.results
#disp = rslt.displacement()
#fldC = disp.outputs.fields_container()
#fld = fldC[0]                    
#result = mdl.results


rsetMax=result.nsets-1

# Get nodal displacements
nnum,ndisp = result.nodal_displacement(rsetMax)

# Plot nodal solution
# result.plot_nodal_solution(rsetMax,background='w',show_edges=True,show_displacement=True)

# Get nodes original position
nodes = result.mesh.nodes

nodeCnt = len(nodes)
newPos = nodes  # Store original position
lastTStep=-1

# Now Iterate over time step
start = 1
rsets=range(1,rsetMax+1,10)

doCombined = True

for rset in rsets:      
    # Get corresponding time info
    tStep = result.solution_info(rset)['timfrq']
    
    # Don't export too many solutions in early stage

    cr,lastTStep = can_reject(tStep,lastTStep)
    if(cr==True):
        print("--Reject Load Set :%5i, tStep: %10.1f" % (rset, tStep))
        continue                # Reject exporting this TimeStep
    else:
        print("++Accept Load Set :%5i, tStep: %10.1f" % (rset, tStep))
        
    tStepStr = "%08.1f" % (tStep)
    
    # Get nodal solutions, along with nodal numbers
    nodeNum, nodeDisp = result.nodal_displacement(rset)   # first set
    nodeNum, nodeTemp = result.nodal_temperature(rset)
    isothermTemp = nodeTemp[1]                          # Nodal temp
    # Load factor from solution
    #lfact = result.solution_info(rset)['lfactn']
    #print(lfact)
                                  
       
    # Using info https://www.w3schools.com/python/python_file_write.asp 
    fullname=outputDir+outputFile+"_"+ tStepStr +".csv"
    f=open(fullname,"w")  
    
    print("%s %68s" % ('!',"Nodal Information Dump"),file=f)
    print("%s %58s%10i" % ('!',"Total Nodes =", nodeCnt),file=f)
    if(doCombined):
        print("%s%9s%20s%20s%20s" % ('!',"Node","X","Y","Z"),file=f)
        print("nblock,3,,%i" % (nodeCnt),file=f)
        print("(1i9,3e20.9e3)",file=f)
    
    else:
        print("%s%9s%20s%20s%20s%20s%20s%20s" % ('!',"Node","X","Y","Z","UX","UY","UZ"),file=f)
        print("nblock,3,,%i" % (nodeCnt),file=f)
        print("(1i9,6e20.9e3)",file=f)
        
    for j in nodeNum:
        if(doCombined):
            print("%9i%20.9E%20.9E%20.9E" % (j,nodes[j-1,0]+nodeDisp[j-1,0],nodes[j-1,1]+nodeDisp[j-1,1],nodes[j-1,2]+nodeDisp[j-1,2]),file=f)
        else:
            print("%9i%20.9E%20.9E%20.9E%20.9E%20.9E%20.9E" % (j,nodes[j-1,0],nodes[j-1,1],nodes[j-1,2],nodeDisp[j-1,0],nodeDisp[j-1,1],nodeDisp[j-1,2]),file=f)
        
    print("-1",file=f)
    print("! ====================================================================",file=f)
    f.close()



    


